
import { University, Profession } from './types';

// Educational logo (Graduation Cap) as SVG data URI
export const LOGO_URL = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%232563eb' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M22 10v6M2 10l10-5 10 5-10 5z'/%3E%3Cpath d='M6 12v5c3 3 9 3 12 0v-5'/%3E%3C/svg%3E";

// Default values for universities that don't have specific data overrides
const DEFAULTS = {
  requirements: [
    "Аттестат о среднем образовании (оригинал)",
    "Сертификат ЕНТ (минимальный балл: 50, Медицина: 70)",
    "Удостоверение личности (копия)",
    "Медицинская справка форма 075/у",
    "6 фотографий размером 3х4"
  ],
  procedure: [
    "Регистрация в базе абитуриентов вуза (онлайн/офлайн).",
    "Сдача документов в приемную комиссию.",
    "Подача заявления на конкурс государственных грантов (через eGov, июль).",
    "Заключение договора на платное отделение (если без гранта).",
    "Зачисление и оплата (август)."
  ],
  scholarships: [
    "Государственный образовательный грант (полное покрытие + стипендия ~41 000 ₸)",
    "Повышенная стипендия (для отличников +15%)",
    "Президентская стипендия (за особые заслуги)",
    "Гранты ректора (внутренние)",
    "Скидки для социально уязвимых категорий"
  ],
  achievements: [
    "Высокий уровень трудоустройства выпускников",
    "Аккредитация независимых агентств (IQAA, IAAR)",
    "Сотрудничество с ведущими предприятиями региона"
  ]
};

export const UNIVERSITIES: University[] = [
  // --- АСТАНА ---
  {
    id: 'nu',
    name: 'Nazarbayev University',
    shortName: 'NU',
    location: 'Астана',
    description: 'Флагман высшего образования Казахстана. Nazarbayev University — это современный исследовательский университет международного уровня. Обучение ведется полностью на английском языке по принципам академической честности и меритократии.',
    founded: 2010,
    ranking: 1,
    students: 6500,
    tuitionAvg: 'от 5 000 000 ₸',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=1200',
    logo: 'NU',
    mission: 'Стать моделью реформы высшего образования и научным центром Казахстана.',
    programs: [
      { name: 'Computer Science', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Изучение алгоритмов, ИИ и разработки ПО.' },
      { name: 'Robotics', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Мехатроника и автоматизация систем.' },
      { name: 'Civil Engineering', degree: 'Bachelor', duration: '4 года', language: 'English' },
    ],
    partners: ['Duke', 'NUS', 'Cambridge', 'UCL'],
    admissionDeadlines: '15.04 (NUET)',
    category: 'National',
    achievements: [
      "Топ-30% исследовательских вузов Азии",
      "Аккредитация международных агентств",
      "Преподаватели из 50+ стран мира"
    ],
    admissionRequirements: [
      "IELTS 6.5 (не менее 6.0 по секциям)",
      "SAT Subject Tests / NUET",
      "Мотивационное письмо",
      "Интервью (для некоторых программ)"
    ],
    admissionProcedure: [
      "Онлайн регистрация на portal.nu.edu.kz",
      "Загрузка сканов документов и сертификатов",
      "Сдача вступительных экзаменов NUET (если нет SAT)",
      "Рассмотрение заявки приемной комиссией",
      "Получение приглашения (Offer letter)"
    ],
    scholarships: [
      "Грант 'Назарбаев Университет' (100% покрытие обучения)",
      "Стипендия Abay Kunanbayev",
      "Социальные гранты Yessenov Foundation"
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
        website: 'https://nu.edu.kz',
        phone: '+7 (7172) 70 66 88',
        email: 'info_admissions@nu.edu.kz',
        address: 'г. Астана, пр. Кабанбай батыра, 53'
    }
  },
  {
    id: 'enu',
    name: 'Евразийский национальный университет им. Л.Н. Гумилева',
    shortName: 'ЕНУ',
    location: 'Астана',
    description: 'Один из ведущих классических университетов Казахстана, входящий в топ мировых рейтингов QS. Является центром евразийской науки и культуры, активно развивает международное сотрудничество.',
    founded: 1996,
    ranking: 3,
    students: 20000,
    tuitionAvg: '1 000 000 – 1 300 000 ₸',
    image: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?auto=format&fit=crop&q=80&w=1200',
    logo: 'ENU',
    mission: 'Генерация знаний и подготовка конкурентоспособных кадров для устойчивого развития Евразии.',
    programs: [
      { name: 'Международные отношения', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' },
      { name: 'Архитектура', degree: 'Bachelor', duration: '5 лет', language: 'KZ/RU' },
      { name: 'Информационные системы', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' }
    ],
    partners: ['RUDN', 'Warsaw Univ', 'MGU'],
    doubleDegree: [
      { partner: 'РУДН (Россия)', program: 'Международное право', country: 'RU' },
      { partner: 'Warsaw University', program: 'International Relations', country: 'PL' }
    ],
    admissionDeadlines: '25.08',
    category: 'National',
    achievements: ["QS World Ranking Top 350", "Лидер по количеству грантов в РК", "QS Stars - 4 звезды"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://enu.kz',
        phone: '+7 (7172) 70 95 00',
        email: 'enu@enu.kz',
        address: 'г. Астана, ул. Сатпаева, 2'
    }
  },
  {
    id: 'kazatu',
    name: 'Казахский агротехнический исследовательский университет им. С. Сейфуллина',
    shortName: 'КазАТИУ',
    location: 'Астана',
    description: 'Крупнейший аграрный вуз Центрального Казахстана со статусом исследовательского университета. Лидер в области сельскохозяйственных наук, ветеринарии и биотехнологий.',
    founded: 1957,
    ranking: 12,
    students: 12000,
    tuitionAvg: '800 000 – 950 000 ₸',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200',
    logo: 'KATU',
    mission: 'Интеграция образования, науки и производства для развития АПК страны.',
    programs: [
      { name: 'Агрономия', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Ветеринария', degree: 'Bachelor', duration: '5 лет', language: 'KZ/RU' },
      { name: 'Технический сервис в АПК', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['UC Davis', 'AgroParisTech'],
    admissionDeadlines: '20.08',
    category: 'State',
    achievements: ["Статус исследовательского университета", "Собственные агрополигоны", "Лидер аграрной науки"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://kazatu.edu.kz',
        phone: '+7 (7172) 31 75 56',
        email: 'katu@katu.kz',
        address: 'г. Астана, пр. Женис, 62'
    }
  },
  {
    id: 'aitu',
    name: 'Astana IT University',
    shortName: 'AITU',
    location: 'Астана',
    description: 'Инновационный IT-университет, расположенный на территории EXPO-2017. Фокус на практических навыках, проектном обучении и цифровой экономике. Программы реализуются за 3 года (триместры).',
    founded: 2019,
    ranking: 10,
    students: 4000,
    tuitionAvg: '1 600 000 ₸',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1200',
    logo: 'AITU',
    mission: 'Подготовка цифровой элиты для трансформации экономики Казахстана.',
    programs: [
      { name: 'Software Engineering', degree: 'Bachelor', duration: '3 года', language: 'English', description: 'Разработка ПО, архитектура систем, DevOps.' },
      { name: 'Big Data Analysis', degree: 'Bachelor', duration: '3 года', language: 'English', description: 'Анализ данных, ML и AI.' },
      { name: 'Cybersecurity', degree: 'Bachelor', duration: '3 года', language: 'English', description: 'Защита информации и сетевая безопасность.' }
    ],
    partners: ['Cisco', 'Huawei', 'Kaspersky', '1C'],
    admissionDeadlines: '10.08',
    category: 'Private',
    achievements: ["Лучший IT вуз по версии работодателей 2023", "Расположение в EXPO центре", "Программы за 3 года (интенсив)"],
    admissionRequirements: ["ЕНТ (проф. предметы: Информатика)", "IELTS не требуется (но приветствуется)", "Собеседование (опционально)"],
    admissionProcedure: [
      "Сдача ЕНТ (Мат + Информатика)",
      "Подача на целевой грант AITU (внутренний конкурс)",
      "Подача на гос. грант",
      "Заключение договора"
    ],
    scholarships: ["Государственные гранты", "Внутренние гранты AITU Partners", "Скидки за призовые места в олимпиадах"],
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://astanait.edu.kz',
        phone: '+7 (7172) 64 57 10',
        email: 'info@astanait.edu.kz',
        address: 'г. Астана, пр. Мангилик Ел, С1.1 (EXPO)'
    }
  },
  {
    id: 'mua',
    name: 'Медицинский университет Астана',
    shortName: 'МУА',
    location: 'Астана',
    description: 'Ведущий медицинский вуз столицы, тесно сотрудничающий с Национальным медицинским холдингом. Клиническая практика проходит в передовых клиниках города.',
    founded: 1964,
    ranking: 19,
    students: 8000,
    tuitionAvg: '1 100 000 – 1 400 000 ₸',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=1200',
    logo: 'MUA',
    mission: 'Подготовка врачей новой формации, ориентированных на пациента и науку.',
    programs: [
      { name: 'Общая медицина', degree: 'Bachelor', duration: '6 лет', language: 'KZ/RU/EN' },
      { name: 'Стоматология', degree: 'Bachelor', duration: '5 лет', language: 'KZ/RU' },
      { name: 'Фармация', degree: 'Bachelor', duration: '5 лет', language: 'KZ/RU' }
    ],
    partners: ['Sapienza Rome', 'Seoul National Univ'],
    admissionDeadlines: '20.07',
    category: 'Medical',
    achievements: ["Лидер по трудоустройству врачей", "Собственный симуляционный центр"],
    admissionRequirements: [...DEFAULTS.requirements, "Психометрический тест (допуск к конкурсу)"],
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://amu.edu.kz',
        phone: '+7 (7172) 53 94 24',
        email: 'info@amu.kz',
        address: 'г. Астана, ул. Бейбитшилик, 49А'
    }
  },
  {
    id: 'kazgyu',
    name: 'Университет КАЗГЮУ имени М.С. Нарикбаева',
    shortName: 'KAZGUU',
    location: 'Астана',
    description: 'Лидер юридического образования в стране. Также имеет сильную международную бизнес-школу и школу либеральных искусств. Высокие стандарты качества и академической честности.',
    founded: 1994,
    ranking: 8,
    students: 5000,
    tuitionAvg: '1 300 000 – 2 000 000 ₸',
    image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&q=80&w=1200',
    logo: 'KAZGUU',
    mission: 'Служение правосудию и обществу через качественное образование.',
    programs: [
      { name: 'Юриспруденция', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' },
      { name: 'Международное право', degree: 'Bachelor', duration: '4 года', language: 'EN' },
      { name: 'Финансы (ACCA)', degree: 'Bachelor', duration: '4 года', language: 'EN' }
    ],
    partners: ['HSE Moscow', 'Oxford (partners)', 'Penn State'],
    doubleDegree: [
       { partner: 'Hof University', program: 'Business Administration', country: 'DE' },
       { partner: 'Solbridge School', program: 'International Business', country: 'KR' }
    ],
    admissionDeadlines: '20.08',
    category: 'Private',
    achievements: ["ACCA аккредитация", "FIBAA аккредитация", "Лучшая школа права в СНГ"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: ["KAZGUU Endowment", "Гранты ректора", "Корпоративные стипендии"],
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://kazguu.kz',
        phone: '+7 (7172) 70 30 30',
        email: 'info@kazguu.kz',
        address: 'г. Астана, шоссе Коргалжын, 8'
    }
  },

  // --- АЛМАТЫ ---
  {
    id: 'kaznu',
    name: 'Казахский Национальный Университет им. аль-Фараби',
    shortName: 'КазНУ',
    location: 'Алматы',
    description: 'Старейший и крупнейший классический университет страны. Обладает огромным кампусом "Казгуград" в предгорьях Заилийского Алатау. Лидер по количеству научных публикаций.',
    founded: 1934,
    ranking: 2,
    students: 25000,
    tuitionAvg: '1 200 000 – 1 600 000 ₸',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=1200',
    logo: 'KazNU',
    mission: 'Формирование интеллектуального потенциала нации и интеграция в мировое образовательное пространство.',
    programs: [
      { name: 'Физика', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Востоковедение', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Биотехнология', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' }
    ],
    partners: ['MSU', 'Osaka Univ', 'Columbia Univ'],
    admissionDeadlines: '20.08',
    category: 'National',
    achievements: ["Top 150 QS World Ranking", "Глобальный Хаб ООН", "Самый большой кампус в ЦА (Казгуград)"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://kaznu.kz',
        phone: '+7 (727) 377 33 33',
        email: 'info@kaznu.kz',
        address: 'г. Алматы, пр. аль-Фараби, 71'
    }
  },
  {
    id: 'satbayev',
    name: 'Satbayev University (КазНИТУ)',
    shortName: 'Satbayev',
    location: 'Алматы',
    description: 'Главный технический вуз страны, первый исследовательский университет. Основной поставщик инженерных кадров для промышленности, нефтегаза и горного дела.',
    founded: 1934,
    ranking: 4,
    students: 15000,
    tuitionAvg: '1 000 000 – 1 200 000 ₸',
    image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=1200',
    logo: 'SU',
    mission: 'Научное и инженерное обеспечение промышленного развития Казахстана.',
    programs: [
      { name: 'Нефтяная инженерия', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' },
      { name: 'Робототехника и мехатроника', degree: 'Bachelor', duration: '4 года', language: 'EN' },
      { name: 'Геология', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['Colorado School of Mines', 'Penn State'],
    doubleDegree: [
      { partner: 'City, University of London', program: 'Project Management', country: 'UK' },
      { partner: 'Hof University', program: 'Computer Science', country: 'DE' }
    ],
    admissionDeadlines: '15.08',
    category: 'National',
    achievements: ["Статус исследовательского университета", "Лидер по патентам", "Сотрудничество с Казатомпром"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://satbayev.university',
        phone: '+7 (727) 292 60 25',
        email: 'info@satbayev.university',
        address: 'г. Алматы, ул. Сатпаева, 22'
    }
  },
  {
    id: 'kbtu',
    name: 'Казахстанско-Британский технический университет',
    shortName: 'КБТУ',
    location: 'Алматы',
    description: 'Элитный технический вуз. Лучшие кадры для IT и нефтегазового сектора. Обучение ведется на английском языке. Тесная связь с индустрией (КМГ, Тенгизшевройл).',
    founded: 2001,
    ranking: 6,
    students: 4000,
    tuitionAvg: '2 400 000 – 3 600 000 ₸',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200',
    logo: 'KBTU',
    mission: 'Подготовка лидеров в сфере технологий и бизнеса.',
    programs: [
      { name: 'Information Systems', degree: 'Bachelor', duration: '4 года', language: 'English' },
      { name: 'Petroleum Engineering', degree: 'Bachelor', duration: '4 года', language: 'English' },
      { name: 'Management', degree: 'Bachelor', duration: '4 года', language: 'English' }
    ],
    partners: ['UoL (University of London)', 'Harvard Business School (affiliate)'],
    doubleDegree: [
       { partner: 'University of London (UoL)', program: 'Economics & Data Science', country: 'UK' },
       { partner: 'Geneva Business School', program: 'Finance', country: 'CH' }
    ],
    admissionDeadlines: '10.07',
    category: 'Private',
    achievements: ["Аккредитация ABET (единственный в РК по IT)", "Трудоустройство в Big 4, Google, Facebook", "Двойной диплом с LSE"],
    admissionRequirements: ["ЕНТ", "IELTS 5.5+", "Математика (профильный предмет)", "Внутренний экзамен по математике (для гранта)"],
    admissionProcedure: DEFAULTS.procedure,
    scholarships: ["Гранты КБТУ", "Гранты компаний-партнеров (Тенгизшевройл, КазМунайГаз)", "Спортсменские гранты"],
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://kbtu.edu.kz',
        phone: '+7 (727) 357 42 42',
        email: 'info@kbtu.kz',
        address: 'г. Алматы, ул. Толе би, 59'
    }
  },
  {
    id: 'kimep',
    name: 'Университет КИМЭП',
    shortName: 'KIMEP',
    location: 'Алматы',
    description: 'Ведущий вуз североамериканского образца в СНГ. Специализируется на бизнесе, праве и социальных науках. Обучение полностью на английском языке.',
    founded: 1992,
    ranking: 7,
    students: 3500,
    tuitionAvg: '3 500 000 – 4 200 000 ₸',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1200',
    logo: 'KIMEP',
    mission: 'Воспитание образованных граждан и улучшение качества жизни в Казахстане.',
    programs: [
      { name: 'Accounting and Audit', degree: 'Bachelor', duration: '4 года', language: 'English' },
      { name: 'Marketing', degree: 'Bachelor', duration: '4 года', language: 'English' },
      { name: 'International Relations', degree: 'Bachelor', duration: '4 года', language: 'English' }
    ],
    partners: ['Yonsei', 'Humboldt Univ', 'Glasgow Univ'],
    doubleDegree: [
      { partner: 'Cass Business School', program: 'Marketing', country: 'UK' },
      { partner: 'IÉSEG School of Management', program: 'Management', country: 'FR' }
    ],
    admissionDeadlines: '15.07',
    category: 'Private',
    achievements: ["Лидер бизнес-образования", "Высочайшие зарплаты выпускников в консалтинге", "Аккредитации всех программ"],
    admissionRequirements: ["IELTS 6.0+", "Аттестат", "Внутренний тест KEPT (если нет IELTS)"],
    admissionProcedure: ["Онлайн заявка", "Тестирование KEPT (опционально)", "Интервью"],
    scholarships: ["Гранты президента КИМЭП (100%)", "Need-based financial aid", "Merit-based scholarships"],
    dormitory: true,
    militaryDept: false,
    contacts: {
        website: 'https://kimep.kz',
        phone: '+7 (727) 270 42 13',
        email: 'uao@kimep.kz',
        address: 'г. Алматы, пр. Абая, 2'
    }
  },
  {
    id: 'iitu',
    name: 'Международный университет информационных технологий',
    shortName: 'MUIT',
    location: 'Алматы',
    description: 'Первый специализированный IT-университет в Центральной Азии. Сильная база программирования и кибербезопасности. Активно участвует в чемпионатах по спортивному программированию.',
    founded: 2009,
    ranking: 9,
    students: 5000,
    tuitionAvg: '1 800 000 ₸',
    image: 'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&q=80&w=1200',
    logo: 'IITU',
    mission: 'Подготовка квалифицированных IT-специалистов международного уровня.',
    programs: [
      { name: 'Computer Science', degree: 'Bachelor', duration: '4 года', language: 'English' },
      { name: 'Software Engineering', degree: 'Bachelor', duration: '4 года', language: 'English' },
      { name: 'IT Management', degree: 'Bachelor', duration: '4 года', language: 'English' }
    ],
    partners: ['Carnegie Mellon (partners)', 'iCarnegie'],
    admissionDeadlines: '20.08',
    category: 'Private',
    achievements: ["Аккредитация ASIIN", "Лучшие команды по спортивному программированию (ACM ICPC)", "Трудоустройство 90%+"],
    admissionRequirements: ["ЕНТ (Мат-Инф)", "Собеседование (для внутренних грантов)"],
    admissionProcedure: DEFAULTS.procedure,
    scholarships: ["Гос. гранты", "Гранты спонсоров", "Скидки за отличную учебу"],
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://iitu.edu.kz',
        phone: '+7 (727) 320 00 00',
        email: 'info@iitu.edu.kz',
        address: 'г. Алматы, ул. Манаса, 34/1'
    }
  },
  {
    id: 'narxoz',
    name: 'Университет Нархоз',
    shortName: 'Narxoz',
    location: 'Алматы',
    description: 'Современный экономический университет, прошедший полную трансформацию. Новый эко-кампус, западные стандарты обучения и фокус на устойчивое развитие.',
    founded: 1963,
    ranking: 13,
    students: 7000,
    tuitionAvg: '1 300 000 – 1 800 000 ₸',
    image: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&q=80&w=1200',
    logo: 'Narxoz',
    mission: 'Вдохновлять на обучение и исследования для устойчивого будущего.',
    programs: [
      { name: 'Экономика', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' },
      { name: 'Финансы', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' },
      { name: 'Маркетинг', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' }
    ],
    partners: ['Coventry Univ', 'Penn State'],
    doubleDegree: [
       { partner: 'Coventry University', program: 'Global Business Management', country: 'UK' },
       { partner: 'La Rochelle', program: 'Tourism', country: 'FR' }
    ],
    admissionDeadlines: '25.08',
    category: 'Private',
    achievements: ["FIBAA аккредитация", "QS Stars - 4 звезды", "Лучший 'Зеленый кампус'"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: ["Гранты Нархоза", "Стипендия Булата Утемуратова", "Скидки за IELTS"],
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://narxoz.kz',
        phone: '+7 (727) 377 11 11',
        email: 'info@narxoz.kz',
        address: 'г. Алматы, ул. Жандосова, 55'
    }
  },
  {
    id: 'almau',
    name: 'Almaty Management University',
    shortName: 'AlmaU',
    location: 'Алматы',
    description: 'Первый предпринимательский вуз Казахстана. Лидер бизнес-образования (MBA, DBA). Фокус на развитии предпринимательского мышления и мягких навыков.',
    founded: 1988,
    ranking: 14,
    students: 4500,
    tuitionAvg: '1 900 000 – 2 200 000 ₸',
    image: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&q=80&w=1200',
    logo: 'AlmaU',
    mission: 'Делаем мир лучше через развитие предпринимательства и знаний.',
    programs: [
      { name: 'Менеджмент', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' },
      { name: 'Предпринимательство', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Ресторанное дело', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['Arizona State University (Cintana)', 'Emlyon'],
    doubleDegree: [
       { partner: 'Arizona State University (ASU)', program: 'Global Management', country: 'USA' },
       { partner: 'Global Business School Barcelona', program: 'BBA', country: 'ES' }
    ],
    admissionDeadlines: '20.08',
    category: 'Private',
    achievements: ["AMBA аккредитация (MBA)", "Стратегическое партнерство с ASU (США)"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: ["Предпринимательские гранты", "Скидки за успеваемость"],
    dormitory: true,
    militaryDept: false,
    contacts: {
        website: 'https://almau.edu.kz',
        phone: '+7 (727) 313 30 90',
        email: 'admission@almau.edu.kz',
        address: 'г. Алматы, ул. Розыбакиева, 227'
    }
  },
  {
    id: 'turan',
    name: 'Университет Туран',
    shortName: 'Turan',
    location: 'Алматы',
    description: 'Инновационно-предпринимательский университет полного цикла (лицей-колледж-вуз-магистратура-PhD). Сильные направления: туризм, кино и ТВ, психология, IT.',
    founded: 1992,
    ranking: 15,
    students: 6000,
    tuitionAvg: '900 000 – 1 100 000 ₸',
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&q=80&w=1200',
    logo: 'Turan',
    mission: 'Создавать возможности для успеха каждого.',
    programs: [
      { name: 'Режиссура', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Туризм', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Психология', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['MSU', 'University of Applied Sciences Europe'],
    admissionDeadlines: '25.08',
    category: 'Private',
    tourUrl: 'https://turan.edu.kz/ru/3dtour/',
    achievements: ["Собственная киностудия", "Apple Training Center", "Лидер в туризме"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: ["Гранты ректора Туран", "Скидки 'Алтын Белгі'"],
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://turan.edu.kz',
        phone: '+7 (727) 260 40 00',
        email: 'info@turan.edu.kz',
        address: 'г. Алматы, ул. Сатпаева, 16А'
    }
  },
  {
    id: 'aupet',
    name: 'Алматинский университет энергетики и связи им. Г. Даукеева',
    shortName: 'АУЭС',
    location: 'Алматы',
    description: 'Главный вуз энергетиков, связистов и IT-специалистов в области телекоммуникаций. Сложное, но качественное техническое образование. Выпускники востребованы в KEGOC, Казахтелеком.',
    founded: 1975,
    ranking: 16,
    students: 8000,
    tuitionAvg: '950 000 – 1 200 000 ₸',
    image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=1200',
    logo: 'AUPET',
    mission: 'Подготовка элиты инженерных кадров для цифровой энергетики.',
    programs: [
      { name: 'Теплоэнергетика', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Электроэнергетика', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Радиотехника и электроника', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['MPEI', 'Schneider Electric'],
    admissionDeadlines: '15.08',
    category: 'State',
    achievements: ["Учебные центры Cisco, Huawei, Schneider Electric", "95% трудоустройство по специальности"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://aues.edu.kz',
        phone: '+7 (727) 323 11 75',
        email: 'aues@aues.kz',
        address: 'г. Алматы, ул. Байтурсынова, 126'
    }
  },
  {
    id: 'atu',
    name: 'Алматинский технологический университет',
    shortName: 'АТУ',
    location: 'Алматы',
    description: 'Лидер в подготовке кадров для пищевой, перерабатывающей и легкой промышленности. Сочетание инженерии, технологий и сервиса.',
    founded: 1957,
    ranking: 30,
    students: 7000,
    tuitionAvg: '800 000 – 1 000 000 ₸',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=1200',
    logo: 'ATU',
    mission: 'Технологии качества жизни.',
    programs: [
      { name: 'Технология продовольственных продуктов', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Дизайн одежды', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Ресторанное дело', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['Institut Paul Bocuse'],
    admissionDeadlines: '20.08',
    category: 'State',
    achievements: ["Собственные производственные цеха", "Международные стажировки для технологов"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: false,
    contacts: {
        website: 'https://atu.edu.kz',
        phone: '+7 (727) 293 52 96',
        email: 'info@atu.edu.kz',
        address: 'г. Алматы, ул. Толе би, 100'
    }
  },
  {
    id: 'kazgasa',
    name: 'КазГАСА (Каз. головная арх.-строит. академия)',
    shortName: 'KazGASA',
    location: 'Алматы',
    description: 'Главный архитектурно-строительный вуз Казахстана. Творческая и инженерная элита строительства. Единственный вуз, имеющий международную аккредитацию RIBA.',
    founded: 1980,
    ranking: 20,
    students: 6000,
    tuitionAvg: '1 200 000 – 1 500 000 ₸',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&q=80&w=1200',
    logo: 'KG',
    mission: 'Строим будущее, сохраняя традиции.',
    programs: [
      { name: 'Архитектура', degree: 'Bachelor', duration: '5 лет', language: 'KZ/RU' },
      { name: 'Дизайн', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Строительство', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['RIBA', 'Politecnico di Milano'],
    admissionDeadlines: '10.07 (Творческие)',
    category: 'Private',
    achievements: ["Аккредитация ЮНЕСКО-МСА", "Золотые медали на архитектурных биеннале"],
    admissionRequirements: [...DEFAULTS.requirements, "Творческие экзамены (Рисунок, Черчение)"],
    admissionProcedure: [
        "Сдача творческих экзаменов в вузе (июль)",
        ...DEFAULTS.procedure.slice(2)
    ],
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://kazgasa.kz',
        phone: '+7 (727) 309 60 00',
        email: 'info@kazgasa.kz',
        address: 'г. Алматы, ул. Рыскулбекова, 28'
    }
  },
  {
    id: 'sdu',
    name: 'SDU University',
    shortName: 'SDU',
    location: 'Каскелен',
    description: 'Современный кампус мирового уровня в пригороде Алматы. Сильные направления: IT, право, педагогика, филология. Обучение преимущественно на английском языке.',
    founded: 1996,
    ranking: 11,
    students: 8000,
    tuitionAvg: '1 500 000 – 2 000 000 ₸',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=1200',
    logo: 'SDU',
    mission: 'Excellence in education.',
    programs: [
      { name: 'Computer Science', degree: 'Bachelor', duration: '4 года', language: 'English' },
      { name: 'Information Systems', degree: 'Bachelor', duration: '4 года', language: 'English' },
      { name: 'Mathematics', degree: 'Bachelor', duration: '4 года', language: 'English' }
    ],
    partners: ['Suleyman Demirel Univ (Turkey)'],
    admissionDeadlines: '20.08',
    category: 'Private',
    achievements: ["Аккредитация ACQUIN", "Топ-3 педагогический вуз", "Высокая репутация в IT"],
    admissionRequirements: ["ЕНТ", "Внутренний экзамен SPT (SDU Proficiency Test) для скидок"],
    admissionProcedure: ["Регистрация на sdu.edu.kz", "Сдача SPT", "Сдача ЕНТ", "Подача документов"],
    scholarships: ["SDU Grants (до 100%) по результатам SPT", "Гос. гранты", "Скидки победителям олимпиад"],
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://sdu.edu.kz',
        phone: '+7 (727) 307 95 65',
        email: 'info@sdu.edu.kz',
        address: 'Алматинская обл., г. Каскелен, ул. Абылай хана, 1/1'
    }
  },
  
  // --- РЕГИОНАЛЬНЫЕ ---
  {
    id: 'karu',
    name: 'Карагандинский университет имени Е.А. Букетова',
    shortName: 'КарУ',
    location: 'Караганда',
    description: 'Один из крупнейших и старейших вузов страны. Классический университет, центр науки и образования Центрального Казахстана.',
    founded: 1938,
    ranking: 17,
    students: 13000,
    tuitionAvg: '600 000 – 900 000 ₸',
    image: 'https://images.unsplash.com/photo-1543966888-7c1dc482a810?auto=format&fit=crop&q=80&w=1200',
    logo: 'KarU',
    mission: 'Служение науке и образованию во благо общества.',
    programs: [
      { name: 'Физика', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Юриспруденция', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Иностранный язык: два иностранных языка', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['Charles Univ', 'Tomsk State Univ'],
    admissionDeadlines: '25.08',
    category: 'State',
    achievements: DEFAULTS.achievements,
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://buketov.edu.kz',
        phone: '+7 (7212) 31 22 43',
        email: 'kargu@ksu.kz',
        address: 'г. Караганда, ул. Университетская, 28'
    }
  },
  {
    id: 'ktu',
    name: 'Карагандинский технический университет им. А. Сагинова',
    shortName: 'КарТУ',
    location: 'Караганда',
    description: '«Политех». Ведущий технический вуз региона. Кузница кадров для горно-металлургической промышленности и машиностроения.',
    founded: 1953,
    ranking: 18,
    students: 10000,
    tuitionAvg: '800 000 – 950 000 ₸',
    image: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&q=80&w=1200',
    logo: 'KTU',
    mission: 'Инновационное развитие через интеграцию образования, науки и производства.',
    programs: [
      { name: 'Горное дело', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Металлургия', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Транспортная техника', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['ArcelorMittal', 'Kazakhmys'],
    admissionDeadlines: '20.08',
    category: 'State',
    achievements: ["Один из лидеров по трудоустройству технарей", "Корпоративный университет"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://kstu.kz',
        phone: '+7 (7212) 56 03 28',
        email: 'kstu@kstu.kz',
        address: 'г. Караганда, пр. Нурсултана Назарбаева, 56'
    }
  },
  {
    id: 'auezov',
    name: 'Южно-Казахстанский университет им. М. Ауэзова',
    shortName: 'SKU',
    location: 'Шымкент',
    description: 'Крупнейший многопрофильный вуз юга страны. Огромный спектр специальностей от химической технологии до искусства и права.',
    founded: 1943,
    ranking: 5,
    students: 28000,
    tuitionAvg: '550 000 – 750 000 ₸',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&q=80&w=1200',
    logo: 'Auezov',
    mission: 'Формирование человеческого капитала для инновационного развития Южного региона.',
    programs: [
      { name: 'Химическая технология', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Право', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Информатика', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: [],
    admissionDeadlines: '25.08',
    category: 'State',
    achievements: ["Самый большой контингент студентов", "Многопрофильность"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://auezov.edu.kz',
        phone: '+7 (7252) 21 01 41',
        email: 'rector@auezov.edu.kz',
        address: 'г. Шымкент, пр. Тауке хана, 5'
    }
  },
  {
    id: 'yessenov',
    name: 'Yessenov University',
    shortName: 'YU',
    location: 'Актау',
    description: 'Флагман образования Мангистауской области. Специализируется на нефтегазовом деле, морской технике и туризме.',
    founded: 1976,
    ranking: 21,
    students: 6000,
    tuitionAvg: '650 000 – 800 000 ₸',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200',
    logo: 'YU',
    mission: 'Служение региону через развитие человеческого капитала.',
    programs: [
      { name: 'Морская техника и технологии', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Нефтегазовое дело', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['Caspian Offshore'],
    admissionDeadlines: '25.08',
    category: 'State',
    achievements: ["Уникальные морские специальности", "Партнерство с нефтяными гигантами"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://yu.edu.kz',
        phone: '+7 (7292) 42 57 00',
        email: 'info@yu.edu.kz',
        address: 'г. Актау, 32 мкр.'
    }
  },
    {
    id: 'dosmukhamedov',
    name: 'Атырауский университет им. Х. Досмухамедова',
    shortName: 'ASU',
    location: 'Атырау',
    description: 'Главный вуз нефтяной столицы. Педагогика, естественные науки, экономика и журналистика.',
    founded: 1950,
    ranking: 29,
    students: 8000,
    tuitionAvg: '600 000 – 800 000 ₸',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&q=80&w=1200',
    logo: 'ASU',
    mission: 'Качественное образование для процветания региона.',
    programs: [
      { name: 'Педагогика и методика', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' },
      { name: 'Журналистика', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: [],
    admissionDeadlines: '25.08',
    category: 'State',
    achievements: DEFAULTS.achievements,
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://asu.edu.kz',
        phone: '+7 (7122) 27 63 23',
        email: 'kense@asu.edu.kz',
        address: 'г. Атырау, пр. Студенческий, 212'
    }
  },
  {
    id: 'aog',
    name: 'Атырауский университет нефти и газа им. С. Утебаева',
    shortName: 'AOGU',
    location: 'Атырау',
    description: 'Специализированный нефтяной вуз. Единственный профильный университет по подготовке кадров для нефтегазовой отрасли в РК.',
    founded: 1980,
    ranking: 32,
    students: 4000,
    tuitionAvg: '800 000 – 1 200 000 ₸',
    image: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&q=80&w=1200',
    logo: 'AOG',
    mission: 'Индустриальный вуз для нефтегазовой отрасли.',
    programs: [
      { name: 'Геология нефти и газа', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU/EN' },
      { name: 'Бурение нефтяных и газовых скважин', degree: 'Bachelor', duration: '4 года', language: 'KZ/RU' }
    ],
    partners: ['TCO', 'NCOC', 'Schlumberger'],
    admissionDeadlines: '20.08',
    category: 'State',
    achievements: ["Тесные связи с TCO и NCOC", "Современные лаборатории"],
    admissionRequirements: DEFAULTS.requirements,
    admissionProcedure: DEFAULTS.procedure,
    scholarships: DEFAULTS.scholarships,
    dormitory: true,
    militaryDept: true,
    contacts: {
        website: 'https://aogu.edu.kz',
        phone: '+7 (7122) 36 05 06',
        email: 'info@aogu.edu.kz',
        address: 'г. Атырау, мкр. Атырау, 1'
    }
  },

  // =============================================
  // --- ЗАРУБЕЖНЫЕ ВУЗЫ (INTERNATIONAL) ---
  // =============================================
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    shortName: 'MIT',
    location: 'США, Кембридж',
    description: 'Один из ведущих технических университетов мира. MIT — глобальный лидер в области науки, технологий и инженерии. Диплом MIT признаётся работодателями во всём мире и открывает двери в крупнейшие компании и исследовательские центры.',
    founded: 1861,
    ranking: 1,
    students: 11500,
    tuitionAvg: 'от ~$60 000/год',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=1200',
    logo: 'MIT',
    mission: 'Продвижение знаний и образования в науке, технологиях и других областях для блага нации и мира.',
    programs: [
      { name: 'Computer Science & AI', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Лучшая в мире программа по CS и искусственному интеллекту.' },
      { name: 'Electrical Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Системы, схемотехника, робототехника.' },
      { name: 'Physics', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Теоретическая и прикладная физика.' },
    ],
    partners: ['Google', 'NASA', 'Microsoft', 'SpaceX'],
    admissionDeadlines: '01.01 (Regular Decision)',
    category: 'International',
    achievements: [
      'QS World Ranking #1 (12 лет подряд)',
      '100+ лауреатов Нобелевской премии',
      'Крупнейший эндаумент-фонд ($27 млрд)',
    ],
    admissionRequirements: [
      'SAT / ACT (топ-перцентиль)',
      'TOEFL iBT 90+ / IELTS 7.0+',
      'Мотивационное эссе',
      '3 рекомендательных письма',
      'Портфолио проектов / олимпиадные достижения',
    ],
    admissionProcedure: [
      'Подача заявки на my.mit.edu (Early Action — 1 ноября).',
      'Загрузка документов и рекомендаций.',
      'Интервью с alumni (по приглашению).',
      'Решение — декабрь (EA) / март (Regular).',
      'Принятие оффера и оформление визы F-1.',
    ],
    scholarships: [
      'MIT Need-Based Financial Aid (без займов!)',
      'MIT International Student Scholarships',
      'Финансовая помощь иностранным студентам (до 100%)',
      'Стипендии от корпоративных партнёров',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://web.mit.edu',
      phone: '+1 (617) 253-1000',
      email: 'admissions@mit.edu',
      address: '77 Massachusetts Ave, Cambridge, MA 02139, USA',
    }
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    shortName: 'Cambridge',
    location: 'Великобритания',
    description: 'Один из старейших и самых престижных университетов мира с 800-летней историей. Входит в тройку лучших вузов планеты. Отличается уникальной коллегиальной системой обучения и выдающимися академическими традициями.',
    founded: 1209,
    ranking: 2,
    students: 24000,
    tuitionAvg: 'от £31 000/год',
    image: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&q=80&w=1200',
    logo: 'Cam',
    mission: 'Содействие образованию, учению и исследованиям на высшем уровне для блага общества.',
    programs: [
      { name: 'Computer Science (Part IA-IB)', degree: 'Bachelor', duration: '3 года', language: 'English', description: 'Алгоритмы, ИИ, программные системы.' },
      { name: 'Natural Sciences', degree: 'Bachelor', duration: '3 года', language: 'English', description: 'Физика, химия, биохимия, биология.' },
      { name: 'Economics', degree: 'Bachelor', duration: '3 года', language: 'English', description: 'Макро- и микроэкономика, финансы.' },
      { name: 'Law (LLB)', degree: 'Bachelor', duration: '3 года', language: 'English', description: 'Международное и европейское право.' },
    ],
    partners: ['NASA', 'Microsoft Research', 'DeepMind', 'Rolls-Royce'],
    admissionDeadlines: '15.10 (UCAS deadline)',
    category: 'International',
    achievements: [
      'QS World Ranking #2 / Times Higher Education #1',
      '121 Нобелевский лауреат',
      'Alma mater: Ньютон, Дарвин, Хокинг',
    ],
    admissionRequirements: [
      'A-Levels AAA / IB 40-42 баллов',
      'IELTS 7.5+ (6.5+ по каждой секции)',
      'Вступительные тесты (TMUA, ENGAA и др.)',
      'Интервью в колледже Cambridge',
      'Суперкуррикулярные активности по предмету',
    ],
    admissionProcedure: [
      'Выбор колледжа и подача через UCAS (15 октября).',
      'Прохождение предметных вступительных тестов.',
      'Интервью с преподавателями колледжа (декабрь).',
      'Условный оффер (conditional offer).',
      'Подтверждение результатов A-Levels / IB в августе.',
    ],
    scholarships: [
      'Cambridge Trust Scholarships',
      'Gates Cambridge Scholarships (полные)',
      'Commonwealth Scholarships',
      'Chevening Awards (UK Government)',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.cam.ac.uk',
      phone: '+44 (0)1223 337733',
      email: 'admissions@cam.ac.uk',
      address: 'The Old Schools, Trinity Lane, Cambridge CB2 1TN, UK',
    }
  },
  {
    id: 'mgu',
    name: 'Московский государственный университет им. М.В. Ломоносова',
    shortName: 'МГУ',
    location: 'Россия, Москва',
    description: 'Крупнейший и старейший университет России. МГУ — центр российской науки, культуры и образования. Входит в топ-100 мировых рейтингов. Ежегодно принимает студентов из Казахстана по государственным квотам.',
    founded: 1755,
    ranking: 87,
    students: 40000,
    tuitionAvg: 'от 280 000 – 450 000 ₽/год',
    image: 'https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&q=80&w=1200',
    logo: 'МГУ',
    mission: 'Сохранение и приумножение лучших традиций российской науки и образования в интересах общества.',
    programs: [
      { name: 'Прикладная математика и информатика', degree: 'Bachelor', duration: '4 года', language: 'RU', description: 'Математика, программирование, анализ данных.' },
      { name: 'Юриспруденция', degree: 'Bachelor', duration: '4 года', language: 'RU', description: 'Государственное и международное право.' },
      { name: 'Международные отношения', degree: 'Bachelor', duration: '4 года', language: 'RU/EN', description: 'Дипломатия, внешняя политика, МО.' },
      { name: 'Биология', degree: 'Bachelor', duration: '4 года', language: 'RU', description: 'Молекулярная биология, биохимия, экология.' },
    ],
    partners: ['РАН', 'Сколтех', 'Яндекс', 'РФ Правительство'],
    admissionDeadlines: '26.07 (ЕГЭ / вступительные МГУ)',
    category: 'International',
    achievements: [
      'QS World Ranking Top-100',
      'Лучший университет СНГ/России',
      'Крупнейшая научная библиотека (10 млн+ книг)',
    ],
    admissionRequirements: [
      'Диплом / аттестат о среднем образовании',
      'Вступительные экзамены МГУ (доп. испытания)',
      'ЕГЭ / ЕНТ или академическая справка',
      'Нострификация документа об образовании',
    ],
    admissionProcedure: [
      'Подача заявления в деканат выбранного факультета.',
      'Нострификация аттестата в Министерстве просвещения РФ.',
      'Прохождение дополнительных вступительных испытаний МГУ.',
      'Зачисление на конкурсной основе.',
      'Оформление учебной визы и регистрации.',
    ],
    scholarships: [
      'Государственная квота РФ для граждан Казахстана',
      'Стипендия Президента РФ для иностранцев',
      'Именные стипендии МГУ',
      'Общежитие по льготной цене',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.msu.ru',
      phone: '+7 (495) 939-10-00',
      email: 'pk@msu.ru',
      address: 'г. Москва, Ленинские горы, 1, ГСП-1',
    }
  },
  {
    id: 'hse',
    name: 'Национальный исследовательский университет «Высшая школа экономики»',
    shortName: 'НИУ ВШЭ',
    location: 'Россия, Москва',
    description: 'Ведущий университет России в области экономики, социальных наук и IT. ВШЭ — современный исследовательский вуз с сильными программами по Data Science, финансам, праву и дизайну. Активно принимает студентов из Казахстана.',
    founded: 1992,
    ranking: 301,
    students: 47000,
    tuitionAvg: 'от 320 000 – 600 000 ₽/год',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b955?auto=format&fit=crop&q=80&w=1200',
    logo: 'ВШЭ',
    mission: 'Формирование среды для создания знаний, востребованных обществом и экономикой.',
    programs: [
      { name: 'Бизнес-информатика', degree: 'Bachelor', duration: '4 года', language: 'RU', description: 'IT, управление, цифровые технологии в бизнесе.' },
      { name: 'Экономика', degree: 'Bachelor', duration: '4 года', language: 'RU/EN', description: 'Финансы, эконометрика, анализ рынков.' },
      { name: 'Юриспруденция', degree: 'Bachelor', duration: '4 года', language: 'RU', description: 'Частное и публичное право, международное право.' },
      { name: 'Программная инженерия', degree: 'Bachelor', duration: '4 года', language: 'RU/EN', description: 'Разработка ПО, архитектура, DevOps.' },
    ],
    partners: ['Яндекс', 'Сбер', '1С', 'Тинькофф'],
    admissionDeadlines: '29.07 (основная волна)',
    category: 'International',
    achievements: [
      'Лучший вуз СНГ по экономике и социальным наукам',
      'Партнёр Яндекс Образования и Сбера',
      '5-е место в Рейтинге вузов России 2024',
    ],
    admissionRequirements: [
      'Аттестат о среднем образовании',
      'ЕГЭ (для граждан РФ) / вступительные испытания ВШЭ',
      'Нострификация для иностранных граждан',
      'Портфолио (для творческих специальностей)',
    ],
    admissionProcedure: [
      'Регистрация на https://enroll.hse.ru.',
      'Подача документов (онлайн или лично).',
      'Участие в конкурсе индивидуальных достижений.',
      'Нострификация аттестата.',
      'Зачисление и оформление договора.',
    ],
    scholarships: [
      'Квота РФ для казахстанских абитуриентов',
      'Стипендия «Путь в науку» ВШЭ',
      'Гранты для призёров олимпиад',
      'Скидки за высокий балл ЕНТ / аттестат',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.hse.ru',
      phone: '+7 (495) 621-28-73',
      email: 'abitur@hse.ru',
      address: 'г. Москва, ул. Мясницкая, 20',
    }
  },
  {
    id: 'kaist',
    name: 'Korea Advanced Institute of Science and Technology',
    shortName: 'KAIST',
    location: 'Южная Корея, Дэджон',
    description: 'Ведущий технический университет Азии, основанный при поддержке правительства Южной Кореи. KAIST — инновационный хаб в области робототехники, ИИ, полупроводников и биотехнологий. Предоставляет щедрые стипендии иностранным студентам.',
    founded: 1971,
    ranking: 42,
    students: 10000,
    tuitionAvg: 'от $3 000/год (со стипендией — бесплатно)',
    image: 'https://images.unsplash.com/photo-1549057446-9f5c6ac91a04?auto=format&fit=crop&q=80&w=1200',
    logo: 'KAIST',
    mission: 'Стать мировым лидером в науке и технологиях для процветания человечества.',
    programs: [
      { name: 'Computer Science', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'ИИ, машинное обучение, HCI.' },
      { name: 'Electrical Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Полупроводники, робототехника, телекоммуникации.' },
      { name: 'Mechanical Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Механика, автомобилестроение, аэрокосмос.' },
      { name: 'Biomedical Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Биомедицинские устройства, генетика.' },
    ],
    partners: ['Samsung', 'LG', 'Hyundai', 'SK Hynix'],
    admissionDeadlines: '30.09 (Spring) / 28.02 (Fall)',
    category: 'International',
    achievements: [
      'QS World Ranking #42',
      'Топ-10 лучших технических вузов Азии',
      'Уровень трудоустройства 99% (Samsung, Hyundai, Google)',
    ],
    admissionRequirements: [
      'Аттестат о среднем образовании (GPA 3.5+/4.0)',
      'TOEFL iBT 83+ / IELTS 6.5+',
      'SAT (желательно 1400+) или ACT',
      'Мотивационное письмо',
      '2 рекомендательных письма',
    ],
    admissionProcedure: [
      'Регистрация на admissions.kaist.ac.kr.',
      'Загрузка транскриптов, мотивационного письма и рекомендаций.',
      'Рассмотрение заявки (2–3 месяца).',
      'Интервью по Zoom (по необходимости).',
      'Оффер + оформление стипендии и визы D-2.',
    ],
    scholarships: [
      'KAIST Scholarship (100% оплата + проживание для иностр.)',
      'Korean Government Scholarship Program (KGSP)',
      'Global Korea Scholarship (GKS)',
      'Стипендии Samsung и LG (для магистратуры)',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.kaist.ac.kr',
      phone: '+82-42-350-2114',
      email: 'admission@kaist.ac.kr',
      address: '291 Daehak-ro, Yuseong-gu, Daejeon 34141, South Korea',
    }
  },
  {
    id: 'eth-zurich',
    name: 'ETH Zürich — Swiss Federal Institute of Technology',
    shortName: 'ETH Zürich',
    location: 'Швейцария, Цюрих',
    description: 'Один из лучших технических университетов мира, расположенный в сердце Европы. Родина 22 нобелевских лауреатов. ETH Zürich известен сильными программами по инженерии, компьютерным наукам, архитектуре и наукам о Земле. Бакалавриат преподаётся преимущественно на немецком.',
    founded: 1855,
    ranking: 7,
    students: 24500,
    tuitionAvg: 'CHF 730/семестр (~$800)',
    image: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?auto=format&fit=crop&q=80&w=1200',
    logo: 'ETH',
    mission: 'Образование и исследования, служащие обществу с ориентацией на науку и технологии.',
    programs: [
      { name: 'Computer Science', degree: 'Master', duration: '2 года', language: 'English', description: 'Системы, ИИ, распределённые вычисления.' },
      { name: 'Data Science', degree: 'Master', duration: '2 года', language: 'English', description: 'Статистика, ML, Big Data.' },
      { name: 'Civil Engineering', degree: 'Bachelor', duration: '3 года', language: 'Deutsch', description: 'Строительство, геотехника, управление проектами.' },
      { name: 'Architecture', degree: 'Bachelor', duration: '3 года', language: 'Deutsch', description: 'Архитектура, городской дизайн.' },
    ],
    partners: ['IBM', 'ABB', 'Nestlé', 'Roche', 'Google DeepMind'],
    admissionDeadlines: '15.12 (Master) / 30.04 (Bachelor)',
    category: 'International',
    achievements: [
      'QS World Ranking #7 (Европа #1 в IT)',
      '22 нобелевских лауреата (вкл. Эйнштейн)',
      'Самые низкие цены за обучение среди топ-10 мира',
    ],
    admissionRequirements: [
      'Аттестат с отличными оценками (особенно математика и физика)',
      'Немецкий B2+ (для бакалавриата) / Английский C1 (для магистратуры)',
      'TOEFL / IELTS (для магистратуры на английском)',
      'Мотивационное письмо и CV',
      'Рекомендательные письма (для магистратуры)',
    ],
    admissionProcedure: [
      'Регистрация на myStudies.ethz.ch.',
      'Загрузка транскриптов и языковых сертификатов.',
      'Прохождение вступительного экзамена (для бакалавра, не-EU).',
      'Рассмотрение заявки (~8 недель).',
      'Получение оффера и оформление разрешения на пребывание (Aufenthaltsbewilligung).',
    ],
    scholarships: [
      'ETH Excellence Scholarship & Opportunity Programme (ESOP)',
      'Swiss Government Excellence Scholarships',
      'Excellence Masters Scholarships (для магистратуры)',
      'Erasmus+ Grants (для EU-партнёров)',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://ethz.ch',
      phone: '+41 44 632 11 11',
      email: 'admissions@ethz.ch',
      address: 'Rämistrasse 101, 8092 Zürich, Switzerland',
    }
  },
  {
    id: 'skoltech',
    name: 'Сколковский институт науки и технологий',
    shortName: 'Сколтех',
    location: 'Россия, Москва',
    description: 'Международный технологический университет нового поколения, основанный совместно с MIT. Сколтех специализируется исключительно на магистратуре и аспирантуре в области IT, энергетики, биомедицины и космоса. Обучение ведётся на английском языке.',
    founded: 2011,
    ranking: 501,
    students: 2200,
    tuitionAvg: 'Бесплатно (полная стипендия)',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200',
    logo: 'Skol',
    mission: 'Создавать, распространять и применять знания для решения глобальных проблем с фокусом на технологии и предпринимательство.',
    programs: [
      { name: 'Space Science and Technology', degree: 'Master', duration: '2 года', language: 'English', description: 'Спутники, космические аппараты, ДЗЗ.' },
      { name: 'Data Science', degree: 'Master', duration: '2 года', language: 'English', description: 'ML, Big Data, прикладной ИИ.' },
      { name: 'Biotechnology', degree: 'Master', duration: '2 года', language: 'English', description: 'Биомедицина, генные технологии.' },
      { name: 'Energy Science and Technology', degree: 'Master', duration: '2 года', language: 'English', description: 'Нефтегаз, возобновляемая энергетика.' },
    ],
    partners: ['MIT', 'Boeing', 'Shell', 'Яндекс', 'Роскосмос'],
    admissionDeadlines: '01.04 (основная волна)',
    category: 'International',
    achievements: [
      'Основан совместно с MIT (USA)',
      'Полная стипендия для всех студентов (включая иностранцев)',
      'Инновационный кампус в Сколково',
    ],
    admissionRequirements: [
      'Диплом бакалавра (технический / естественнонаучный)',
      'IELTS 6.5+ / TOEFL iBT 85+',
      'GRE / GMAT (желательно)',
      'Мотивационное письмо и резюме (CV)',
      '2 рекомендательных письма',
    ],
    admissionProcedure: [
      'Онлайн заявка на apply.skoltech.ru.',
      'Загрузка диплома, транскриптов, IELTS/TOEFL.',
      'Письменный тест и онлайн-интервью.',
      'Решение приёмной комиссии (~3 недели).',
      'Оформление студенческой визы и регистрации.',
    ],
    scholarships: [
      'Полная стипендия Сколтех (покрывает обучение и проживание)',
      'Гранты Правительства РФ для иностранцев',
      'Корпоративные стипендии от партнёров (Shell, Boeing)',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.skoltech.ru',
      phone: '+7 (495) 280-14-81',
      email: 'ask@skoltech.ru',
      address: 'Территория инновационного центра «Сколково», Большой бульвар, 30, Москва',
    }
  },
  {
    id: 'nus',
    name: 'National University of Singapore',
    shortName: 'NUS',
    location: 'Сингапур',
    description: 'Лучший университет Азии по версии QS 2024. NUS — флагман Сингапура и один из самых инновационных вузов мира. Предлагает сотни программ на английском языке, сильные связи с бизнесом и отличную перспективу трудоустройства в азиатском регионе.',
    founded: 1905,
    ranking: 8,
    students: 40000,
    tuitionAvg: 'SGD 17 000 – 26 000/год (~$13–19 тыс.)',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=1200',
    logo: 'NUS',
    mission: 'Образование глобальных лидеров и пионеров, создающих влияние для Сингапура и мира.',
    programs: [
      { name: 'Computer Science', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'ИИ, кибербезопасность, SE, Data Science.' },
      { name: 'Business Administration', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Управление, маркетинг, предпринимательство.' },
      { name: 'Medicine (MBBS)', degree: 'Bachelor', duration: '5 лет', language: 'English', description: 'Клиническая медицина, хирургия.' },
      { name: 'Law (LLB)', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Международное и деловое право.' },
    ],
    partners: ['Google', 'Alibaba', 'Grab', 'DBS Bank', 'A*STAR'],
    admissionDeadlines: '01.03 (International applicants)',
    category: 'International',
    achievements: [
      'QS World Ranking #8 / Asia #1',
      'Лучший вуз Юго-Восточной Азии 10+ лет',
      '100+ спин-офф стартапов в год',
    ],
    admissionRequirements: [
      'Аттестат с отличными оценками (A-Levels/IB/National exams)',
      'SAT 1400+ / ACT 32+ (для некоторых программ)',
      'IELTS 6.5+ / TOEFL iBT 92+',
      'Мотивационное письмо',
      '1 рекомендательное письмо',
    ],
    admissionProcedure: [
      'Онлайн заявка на admissions.nus.edu.sg.',
      'Загрузка документов, транскриптов, языковых сертификатов.',
      'SAT/ACT баллы (при наличии).',
      'Интервью (для медицины и права).',
      'Оффер + оформление Student\'s Pass (виза).',
    ],
    scholarships: [
      'NUS Scholarships for ASEAN & International Students',
      'ASEAN Undergraduate Scholarship',
      'Science & Technology Undergraduate Scholarship',
      'Singapore Government Scholarships (SPRING)',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.nus.edu.sg',
      phone: '+65 6516 6666',
      email: 'askadmissions@nus.edu.sg',
      address: '21 Lower Kent Ridge Road, Singapore 119077',
    }
  },

  // --- Германия ---
  {
    id: 'tum',
    name: 'Технический университет Мюнхена',
    shortName: 'TU München',
    location: 'Германия, Мюнхен',
    description: 'Лучший технический университет Германии и один из топовых в Европе. TUM входит в элитную группу «Университетов превосходства» Германии. Сильные программы по инженерии, информатике, менеджменту и медицине. Обучение частично на английском, стоимость — практически бесплатная.',
    founded: 1868,
    ranking: 37,
    students: 50000,
    tuitionAvg: 'Семестровый взнос €144 (~$155) + страховка',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&q=80&w=1200',
    logo: 'TUM',
    mission: 'Отличное образование и исследования для устойчивого развития общества.',
    programs: [
      { name: 'Informatics (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English', description: 'ИИ, робототехника, безопасность данных.' },
      { name: 'Electrical Engineering (B.Sc.)', degree: 'Bachelor', duration: '3.5 года', language: 'Deutsch', description: 'Электроника, автоматизация, телекоммуникации.' },
      { name: 'Management & Technology (B.Sc.)', degree: 'Bachelor', duration: '4 года', language: 'English/DE', description: 'Технологический менеджмент, стартапы.' },
      { name: 'Data Engineering & Analytics', degree: 'Master', duration: '2 года', language: 'English', description: 'Big Data, ML, аналитика.' },
    ],
    partners: ['BMW', 'Siemens', 'MAN', 'Microsoft', 'Google'],
    admissionDeadlines: '15.01 (Winter) / 31.05 (Summer)',
    category: 'International',
    achievements: [
      'QS World Ranking #37',
      'Элитный университет Германии (Exzellenzinitiative)',
      '17 нобелевских лауреатов',
    ],
    admissionRequirements: [
      'Аттестат / Диплом бакалавра с высоким GPA',
      'Немецкий B2+ (DSH-2 / TestDaF) для нем. программ',
      'IELTS 6.5+ / TOEFL iBT 88+ для англ. программ',
      'Мотивационное письмо и CV',
      'Рекомендательные письма (для магистратуры)',
    ],
    admissionProcedure: [
      'Регистрация на TUMonline (campus.tum.de).',
      'Подача документов через TUMOnline или uni-assist.de.',
      'Оценка документов приёмной комиссией.',
      'Получение Zulassung (разрешение на обучение).',
      'Подача заявки на студенческую визу (Visum D).',
    ],
    scholarships: [
      'DAAD Scholarship (немецкая служба академических обменов)',
      'Deutschlandstipendium (€300/мес)',
      'TUM Merit Scholarships',
      'Erasmus+ для студентов из стран-партнёров',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.tum.de',
      phone: '+49 89 289-01',
      email: 'studienbuero@tum.de',
      address: 'Arcisstraße 21, 80333 München, Germany',
    }
  },
  {
    id: 'heidelberg',
    name: 'Гейдельбергский университет',
    shortName: 'Heidelberg',
    location: 'Германия, Гейдельберг',
    description: 'Старейший университет Германии (1386 г.) и один из самых престижных в Европе. Особенно силён в медицине, биологии, праве и гуманитарных науках. Расположен в живописном университетском городке. Обучение преимущественно на немецком.',
    founded: 1386,
    ranking: 65,
    students: 30000,
    tuitionAvg: 'Семестровый взнос €185 (~$200)',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&q=80&w=1200',
    logo: 'HD',
    mission: 'Служение истине через науку и образование для общества и будущих поколений.',
    programs: [
      { name: 'Medizin (Staatsexamen)', degree: 'Bachelor', duration: '6 лет', language: 'Deutsch', description: 'Одна из лучших медицинских программ Германии.' },
      { name: 'Biosciences (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English', description: 'Молекулярная биология, биотехнологии, нейронауки.' },
      { name: 'Law (Staatsexamen)', degree: 'Bachelor', duration: '4.5 года', language: 'Deutsch', description: 'Немецкое и европейское право.' },
    ],
    partners: ['DKFZ', 'EMBL', 'Max Planck', 'WHO'],
    admissionDeadlines: '15.07 (Wintersemester) / 15.01 (Sommersemester)',
    category: 'International',
    achievements: [
      'Старейший университет Германии (с 1386 г.)',
      '56 нобелевских лауреатов',
      'Топ медицинская школа Европы',
    ],
    admissionRequirements: [
      'Аттестат с нострификацией (Feststellungsprüfung)',
      'Немецкий C1 (DSH-2 или TestDaF 4×4)',
      'NC (numerus clausus) — высокий средний балл',
      'Мотивационное письмо (для отдельных программ)',
    ],
    admissionProcedure: [
      'Подача через hochschulstart.de (для медицины) или напрямую.',
      'Прохождение Feststellungsprüfung при необходимости.',
      'Запись через uni-assist.de (для иностранцев).',
      'Получение письма о зачислении.',
      'Оформление визы в посольстве Германии.',
    ],
    scholarships: [
      'DAAD Scholarship (полные и частичные)',
      'Heidelberg University Excellence Scholarship',
      'Heinrich Böll Foundation Grants',
      'Konrad Adenauer Foundation Scholarships',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.uni-heidelberg.de',
      phone: '+49 6221 54-0',
      email: 'info@uni-heidelberg.de',
      address: 'Grabengasse 1, 69117 Heidelberg, Germany',
    }
  },

  // --- Турция ---
  {
    id: 'metu',
    name: 'Ближневосточный технический университет',
    shortName: 'METU (ODTÜ)',
    location: 'Турция, Анкара',
    description: 'Ведущий технический университет Турции и всего ближневосточного региона. Обучение ведётся полностью на английском языке — редкость для турецких вузов. Очень популярен среди казахстанских студентов: доступные цены, хорошее качество и диплом международного уровня.',
    founded: 1956,
    ranking: 401,
    students: 30000,
    tuitionAvg: 'от $800 – 2 500/год (иностр. студенты)',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&q=80&w=1200',
    logo: 'METU',
    mission: 'Создание и распространение знаний в области науки и технологий для блага общества.',
    programs: [
      { name: 'Computer Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Разработка ПО, сети, встроенные системы.' },
      { name: 'Electrical & Electronics Eng.', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Электроника, телекоммуникации, схемы.' },
      { name: 'Business Administration', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Управление, финансы, маркетинг.' },
      { name: 'International Relations', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Дипломатия, МО, конфликтология.' },
    ],
    partners: ['NASA', 'CERN', 'Boeing', 'Airbus'],
    admissionDeadlines: '30.06 (Fall) / 30.11 (Spring)',
    category: 'International',
    achievements: [
      'Единственный вуз Турции с обучением полностью на английском',
      'QS World Ranking Top-500',
      'Самый популярный вуз Турции среди иностранных студентов',
    ],
    admissionRequirements: [
      'Аттестат о среднем образовании',
      'SAT 1200+ / ACT 25+ или METU English Proficiency Exam',
      'IELTS 6.5+ / TOEFL iBT 79+',
      'Мотивационное письмо',
    ],
    admissionProcedure: [
      'Онлайн заявка на ois.metu.edu.tr.',
      'Загрузка аттестата, языкового сертификата и мотив. письма.',
      'Сдача вступительного языкового теста METU (при необходимости).',
      'Получение условного оффера.',
      'Оформление студенческой визы Турции.',
    ],
    scholarships: [
      'Türkiye Burslari (полная стипендия Правительства Турции — жильё + стипендия)',
      'METU International Student Scholarship',
      'Скидки за высокий GPA',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.metu.edu.tr',
      phone: '+90 312 210 2000',
      email: 'ois@metu.edu.tr',
      address: 'Dumlupınar Blvd No:1, 06800 Ankara, Turkey',
    }
  },
  {
    id: 'istanbul',
    name: 'Стамбульский университет',
    shortName: 'İÜ',
    location: 'Турция, Стамбул',
    description: 'Один из старейших и крупнейших университетов Турции, расположенный в сердце Стамбула. Привлекает тысячи студентов из Казахстана и Центральной Азии ежегодно. Доступные цены, широкий выбор программ, возможность учиться на русском/казахском в отдельных группах.',
    founded: 1453,
    ranking: 751,
    students: 73000,
    tuitionAvg: 'от $500 – 1 500/год',
    image: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&q=80&w=1200',
    logo: 'İÜ',
    mission: 'Воспитание образованных граждан, служащих Турции и всему человечеству.',
    programs: [
      { name: 'Медицина / Tıp', degree: 'Bachelor', duration: '6 лет', language: 'Türkçe', description: 'Клиническая медицина, диплом признан в РК.' },
      { name: 'Стоматология / Diş Hekimliği', degree: 'Bachelor', duration: '5 лет', language: 'Türkçe', description: 'Терапевтическая и хирургическая стоматология.' },
      { name: 'Юриспруденция / Hukuk', degree: 'Bachelor', duration: '4 года', language: 'Türkçe', description: 'Турецкое и международное право.' },
      { name: 'Экономика / İktisat', degree: 'Bachelor', duration: '4 года', language: 'Türkçe/EN', description: 'Макроэкономика, финансы, мировая экономика.' },
    ],
    partners: ['Erasmus+ (500+ вузов)', 'UN', 'World Bank'],
    admissionDeadlines: '31.07 (осенний семестр)',
    category: 'International',
    achievements: [
      'Крупнейший университет Турции (73 000 студентов)',
      'Один из старейших вузов мира (с 1453 г.)',
      '5 000+ студентов из Казахстана и ЦА ежегодно',
    ],
    admissionRequirements: [
      'Аттестат о среднем образовании (нострификация)',
      'Türkiye Burslari или YÖS (вступительный экзамен для иностранцев)',
      'Языковой экзамен (TÖMER — турецкий, если программа на тур.)',
      'Медицинская справка',
    ],
    admissionProcedure: [
      'Подача заявки через studyinturkey.gov.tr или напрямую.',
      'Участие в конкурсе стипендий Türkiye Burslari (февраль).',
      'Сдача YÖS экзамена (апрель–май).',
      'Зачисление и оформление ВНЖ в Турции.',
    ],
    scholarships: [
      'Türkiye Burslari — полная стипендия (жильё, питание, перелёт)',
      'Скидки для граждан тюркоязычных стран',
      'Гранты TIKA (Турецкое агентство по сотрудничеству)',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.istanbul.edu.tr',
      phone: '+90 212 440 0000',
      email: 'uluslararasi@istanbul.edu.tr',
      address: 'Beyazıt, Fatih, 34116 İstanbul, Turkey',
    }
  },

  // --- Китай ---
  {
    id: 'tsinghua',
    name: 'Университет Цинхуа',
    shortName: 'Tsinghua',
    location: 'Китай, Пекин',
    description: '"Азиатский MIT" — ведущий технический вуз Китая и всей Азии. Активно принимает иностранных студентов, особенно из Казахстана — предоставляются правительственные стипендии КНР. Обучение на английском или китайском. Сильнейшие программы по инженерии, ИИ и бизнесу.',
    founded: 1911,
    ranking: 25,
    students: 47000,
    tuitionAvg: 'CNY 26 000–30 000/год (~$3 500–4 200)',
    image: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?auto=format&fit=crop&q=80&w=1200',
    logo: 'THU',
    mission: 'Самосовершенствование, честность, всесторонность, лидерство — для Китая и мира.',
    programs: [
      { name: 'Computer Science & Technology', degree: 'Bachelor', duration: '4 года', language: 'English/中文', description: 'ИИ, алгоритмы, разработка систем.' },
      { name: 'Civil Engineering', degree: 'Bachelor', duration: '4 года', language: '中文', description: 'Строительство, геотехника, транспорт.' },
      { name: 'Economics & Finance', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Финансы, эконометрика, международная экономика.' },
      { name: 'Architecture', degree: 'Bachelor', duration: '5 лет', language: '中文', description: 'Архитектура, урбанизм, дизайн.' },
    ],
    partners: ['MIT', 'UC Berkeley', 'Oxford', 'Huawei', 'Alibaba'],
    admissionDeadlines: '31.03 (осенний семестр)',
    category: 'International',
    achievements: [
      'QS World Ranking #25',
      'Лучший вуз Китая и Азии (несколько лет)',
      'Партнёр: MIT, Huawei, Google, Alibaba',
    ],
    admissionRequirements: [
      'Аттестат о среднем образовании',
      'HSK 5+ (для программ на китайском)',
      'IELTS 6.5+ / TOEFL iBT 90+ (для английских программ)',
      'Мотивационное письмо и рекомендации',
      'Медицинская справка',
    ],
    admissionProcedure: [
      'Регистрация на is.tsinghua.edu.cn.',
      'Подача заявки на стипендию CSC (до 1 февраля).',
      'Загрузка аттестата, языковых сертификатов, мотив. письма.',
      'Рассмотрение заявки (~2 месяца).',
      'Оффер + оформление учебной визы X1/X2.',
    ],
    scholarships: [
      'Chinese Government Scholarship (CSC) — полная (для граждан КЗ)',
      'Tsinghua University Scholarship for International Students',
      'Silk Road Scholarship (для стран ШОС и Центральной Азии)',
      'Конфуций-Институт Стипендии (для знающих китайский)',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.tsinghua.edu.cn',
      phone: '+86 10 6278-4857',
      email: 'international@tsinghua.edu.cn',
      address: '30 Shuangqing Rd, Haidian District, Beijing 100084, China',
    }
  },
  {
    id: 'beihang',
    name: 'Пекинский авиационно-космический университет',
    shortName: 'BUAA',
    location: 'Китай, Пекин',
    description: 'Ведущий аэрокосмический и технический университет Китая. BUAA — главный поставщик кадров для китайской космической отрасли, авиации и оборонной промышленности. Активно принимает студентов из Казахстана по стипендиям CSC. Популярен среди тех, кто хочет работать в авиа- и нефтегазовой сфере.',
    founded: 1952,
    ranking: 451,
    students: 38000,
    tuitionAvg: 'CNY 25 000–29 000/год (~$3 400–4 000)',
    image: 'https://images.unsplash.com/photo-1569660609-1b7c51e9d1ed?auto=format&fit=crop&q=80&w=1200',
    logo: 'BUAA',
    mission: 'Воспитание элиты аэрокосмической и технической науки для развития Китая.',
    programs: [
      { name: 'Aerospace Engineering', degree: 'Bachelor', duration: '4 года', language: 'English/中文', description: 'Самолётостроение, ракетные двигатели, авионика.' },
      { name: 'Petroleum Engineering', degree: 'Bachelor', duration: '4 года', language: '中文', description: 'Бурение, добыча нефти и газа, геология пласта.' },
      { name: 'Software Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Разработка ПО, встроенные системы, DevOps.' },
      { name: 'Mechanical Engineering', degree: 'Bachelor', duration: '4 года', language: '中文/EN', description: 'Машиностроение, CAD/CAM, робототехника.' },
    ],
    partners: ['Airbus', 'COMAC', 'AVIC', 'Роскосмос', 'Boeing'],
    admissionDeadlines: '15.03 (осенний семестр)',
    category: 'International',
    achievements: [
      'Главный аэрокосмический вуз Китая',
      'Партнёр Airbus, COMAC и Роскосмос',
      'Стипендии CSC для граждан Казахстана',
    ],
    admissionRequirements: [
      'Аттестат о среднем образовании (GPA 75%+)',
      'HSK 4+ (для программ на китайском)',
      'IELTS 6.0+ / TOEFL iBT 80+ (для английских)',
      'Мотивационное письмо',
      'Медицинская справка (форма JW201/JW202)',
    ],
    admissionProcedure: [
      'Подача заявки на ips.buaa.edu.cn.',
      'Заявка на стипендию CSC через csc.edu.cn.',
      'Загрузка всех документов онлайн.',
      'Получение Admission Notice.',
      'Оформление визы X1 + регистрация по прибытии.',
    ],
    scholarships: [
      'Chinese Government Scholarship CSC (полная)',
      'BUAA Presidential Scholarship для иностранцев',
      'Belt & Road Initiative Scholarship',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://ev.buaa.edu.cn',
      phone: '+86 10 8231-6181',
      email: 'ioeng@buaa.edu.cn',
      address: 'No.37 Xueyuan Road, Haidian District, Beijing 100191, China',
    }
  },

  // --- Чехия ---
  {
    id: 'ctu-prague',
    name: 'Чешский технический университет в Праге',
    shortName: 'ČVUT Praha',
    location: 'Чехия, Прага',
    description: 'Один из старейших технических университетов Европы. Расположен в центре Праги — одном из красивейших городов мира. Обучение бесплатно при знании чешского языка. Программы на английском — платные, но доступные. Диплом признаётся в ЕС и Казахстане.',
    founded: 1707,
    ranking: 551,
    students: 18000,
    tuitionAvg: 'Бесплатно (чеш. язык) / €3 000–5 000/год (англ.)',
    image: 'https://images.unsplash.com/photo-1562016600-ece13e8ba570?auto=format&fit=crop&q=80&w=1200',
    logo: 'ČVUT',
    mission: 'Образование инженеров и учёных мирового уровня в традициях европейской науки.',
    programs: [
      { name: 'Software Engineering (B.Sc.)', degree: 'Bachelor', duration: '3 года', language: 'English', description: 'Разработка ПО, архитектура, AI.' },
      { name: 'Civil Engineering', degree: 'Bachelor', duration: '4 года', language: 'Čeština', description: 'Строительство, мосты, дороги, ЖКХ.' },
      { name: 'Mechanical Engineering (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English', description: 'Производство, CAD, автомобилестроение.' },
    ],
    partners: ['Škoda Auto', 'Siemens', 'ABB', 'Bosch', 'ČEZ'],
    admissionDeadlines: '31.03 (осенний семестр)',
    category: 'International',
    achievements: [
      'Старейший технический вуз ЦВЕ (с 1707 г.)',
      'Бесплатное обучение при знании чешского',
      'Диплом ЕС — признаётся по всей Европе',
    ],
    admissionRequirements: [
      'Аттестат с нострификацией в МО Чехии',
      'Чешский B2+ (ÚJOP) для бесплатных программ',
      'IELTS 6.0+ / TOEFL iBT 72+ для англ. программ',
      'Мотивационное письмо',
    ],
    admissionProcedure: [
      'Онлайн заявка на prihlaska.cvut.cz.',
      'Нострификация аттестата (2–3 месяца).',
      'Языковой сертификат или курсы ÚJOP.',
      'Получение подтверждения о зачислении.',
      'Оформление долгосрочной визы D в посольстве ЧР.',
    ],
    scholarships: [
      'Чешские правительственные стипендии для иностранцев (DZS)',
      'ČVUT Merit Scholarships',
      'Erasmus+ Mobility Grants',
      'Вышеградский фонд (V4) стипендии',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.cvut.cz',
      phone: '+420 224 351 111',
      email: 'studijni@cvut.cz',
      address: 'Zikova 1903/4, 166 36 Praha 6-Dejvice, Czech Republic',
    }
  },

  // --- Нидерланды ---
  {
    id: 'delft',
    name: 'Делфтский технический университет',
    shortName: 'TU Delft',
    location: 'Нидерланды, Делфт',
    description: 'Лучший технический университет Нидерландов и один из топ-10 в Европе. TU Delft знаменит программами по аэрокосмосу, гражданскому строительству, архитектуре и компьютерным наукам. Все программы магистратуры ведутся на английском языке.',
    founded: 1842,
    ranking: 49,
    students: 27000,
    tuitionAvg: '€18 750/год (non-EU) / €2 530/год (EU)',
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&q=80&w=1200',
    logo: 'TUDelft',
    mission: 'Наука и технологии для будущего — устойчивое общество через инженерную мысль.',
    programs: [
      { name: 'Aerospace Engineering (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English', description: 'Авиация, ракеты, беспилотники.' },
      { name: 'Computer Science (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English', description: 'ИИ, кибербезопасность, SE.' },
      { name: 'Civil Engineering (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English', description: 'Водные системы, геотехника, транспорт.' },
      { name: 'Architecture & the Built Environment', degree: 'Master', duration: '2 года', language: 'English', description: 'Архитектура, городская среда, устойчивость.' },
    ],
    partners: ['Airbus', 'Shell', 'Philips', 'ASML', 'ING'],
    admissionDeadlines: '01.04 (магистратура)',
    category: 'International',
    achievements: [
      'QS World Ranking #49 / Европа Топ-10 (Инженерия)',
      'Родина многих нидерландских изобретений',
      '100% магистерских программ на английском',
    ],
    admissionRequirements: [
      'Диплом бакалавра по профилю (GPA 75%+)',
      'IELTS 6.5+ / TOEFL iBT 90+',
      'Мотивационное письмо',
      'CV / Resume',
      '2 рекомендательных письма',
    ],
    admissionProcedure: [
      'Онлайн заявка на studielink.nl + TU Delft Portal.',
      'Загрузка транскриптов, диплома, мотив. письма.',
      'Рассмотрение заявки (~6–8 недель).',
      'Получение Letter of Admission.',
      'Оформление MVV-визы или Dutch Residence Permit.',
    ],
    scholarships: [
      'TU Delft Excellence Scholarship (€25 000/год)',
      'Holland Scholarship (€5 000 — единоразово)',
      'Orange Tulip Scholarship (для ряда стран)',
      'Erasmus+ Grants',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.tudelft.nl',
      phone: '+31 15 278 9111',
      email: 'info@tudelft.nl',
      address: 'Mekelweg 5, 2628 CD Delft, Netherlands',
    }
  },

  // --- ОАЭ ---
  {
    id: 'khalifa',
    name: 'Университет Халифа',
    shortName: 'Khalifa Univ.',
    location: 'ОАЭ, Абу-Даби',
    description: 'Ведущий исследовательский университет ОАЭ, специализирующийся на науке, технологиях, инженерии и математике (STEM). Входит в топ-5 вузов арабского мира. Обучение полностью на английском. Щедрые стипендии для иностранных студентов. Тесное сотрудничество с нефтегазовой отраслью (ADNOC, BP).',
    founded: 2007,
    ranking: 201,
    students: 5000,
    tuitionAvg: 'AED 57 000/год (~$15 500) — покрывается стипендией',
    image: 'https://images.unsplash.com/photo-1528702748617-c64d49f918af?auto=format&fit=crop&q=80&w=1200',
    logo: 'KU',
    mission: 'Подготовка учёных и инженеров, двигающих инновации для ОАЭ и региона.',
    programs: [
      { name: 'Petroleum Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Нефтегаз, бурение, пластовые флюиды.' },
      { name: 'Computer Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Кибербезопасность, AI, встроенные системы.' },
      { name: 'Nuclear Engineering', degree: 'Master', duration: '2 года', language: 'English', description: 'Ядерная энергетика, реакторные технологии.' },
      { name: 'Mechanical Engineering', degree: 'Bachelor', duration: '4 года', language: 'English', description: 'Термодинамика, робототехника, CAD.' },
    ],
    partners: ['ADNOC', 'BP', 'Lockheed Martin', 'General Electric'],
    admissionDeadlines: '01.02 (Fall semester)',
    category: 'International',
    achievements: [
      'QS Arab Region #5',
      'Лучший инженерный вуз ОАЭ',
      'Полные стипендии для иностранных студентов',
    ],
    admissionRequirements: [
      'Аттестат с высоким средним баллом (85%+)',
      'SAT 1200+ / ACT 26+ (желательно)',
      'IELTS 6.0+ / TOEFL iBT 79+',
      'Мотивационное письмо',
    ],
    admissionProcedure: [
      'Онлайн заявка на ku.ac.ae.',
      'Загрузка аттестата, языковых сертификатов, мотив. письма.',
      'Рассмотрение заявки на стипендию.',
      'Получение оффера.',
      'Оформление студенческой визы ОАЭ.',
    ],
    scholarships: [
      'KU Full Scholarship (туиция + жильё + стипендия $1500/мес)',
      'ADNOC Scholarship (для нефтегазовых программ)',
      'UAE Centennial Scholarship',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.ku.ac.ae',
      phone: '+971 2 401 8000',
      email: 'admissions@ku.ac.ae',
      address: 'Main Campus, Sas Al Nakhl, Abu Dhabi, UAE',
    }
  },

  // --- Франция ---
  {
    id: 'paris-saclay',
    name: 'Университет Париж-Сакле',
    shortName: 'Paris-Saclay',
    location: 'Франция, Париж',
    description: 'Крупнейший исследовательский университет Франции, объединяющий 10 вузов и 9 национальных лабораторий. Занял первое место в рейтинге Times Higher Education в области физики, математики и химии. Сильные магистерские программы на английском. Обучение частично субсидируется государством.',
    founded: 2015,
    ranking: 69,
    students: 48000,
    tuitionAvg: '€3 770/год (иностр. студенты, фиксированная государственная ставка)',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=1200',
    logo: 'PSaclay',
    mission: 'Мировое лидерство в науке и технологиях через объединение лучших умов Франции.',
    programs: [
      { name: 'Mathematics (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English/Français', description: 'Анализ, топология, математическая физика.' },
      { name: 'Physics (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English', description: 'Квантовая физика, нанотехнологии, астрофизика.' },
      { name: 'Data Science (M.Sc.)', degree: 'Master', duration: '2 года', language: 'English', description: 'ML, статистика, AI.' },
      { name: 'Petroleum Geosciences', degree: 'Master', duration: '2 года', language: 'English', description: 'Геология нефтяных месторождений, сейсмика.' },
    ],
    partners: ['CEA', 'CNRS', 'Airbus', 'EDF', 'Total Energies'],
    admissionDeadlines: '15.04 (для магистратуры)',
    category: 'International',
    achievements: [
      'THE World Ranking #1 в физике и математике',
      'QS World Ranking #69',
      'Объединяет 10 вузов и 9 нац. лабораторий',
    ],
    admissionRequirements: [
      'Диплом бакалавра (или эквивалент) с высоким GPA',
      'IELTS 6.5+ / TOEFL iBT 87+ (для англ. программ)',
      'DELF/DALF B2 (для фр. программ)',
      'Мотивационное письмо',
      '2 рекомендательных письма',
    ],
    admissionProcedure: [
      'Заявка через MonMaster.gouv.fr или напрямую.',
      'Загрузка транскриптов, дипломов, мотив. письма.',
      'Рассмотрение заявки кафедрой.',
      'Получение оффера.',
      'Оформление студенческой визы (Campus France).',
    ],
    scholarships: [
      'Eiffel Excellence Scholarship Programme (полные)',
      'Bourse du gouvernement français (франц. правительство)',
      'Campus France Grants для КЗ',
      'PAUSE Program (для исследователей)',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.universite-paris-saclay.fr',
      phone: '+33 1 69 15 00 00',
      email: 'international@universite-paris-saclay.fr',
      address: '15 Rue Georges Clemenceau, 91400 Orsay, France',
    }
  },

  // --- Польша ---
  {
    id: 'warsaw-tech',
    name: 'Варшавский политехнический университет',
    shortName: 'PW Warszawa',
    location: 'Польша, Варшава',
    description: 'Лучший технический университет Польши. Варшавская политехника очень популярна среди казахстанских студентов: доступные цены, европейский диплом, обучение на русском или английском. Близость к Казахстану по культуре и менталитету. Диплом признаётся в ЕС.',
    founded: 1826,
    ranking: 801,
    students: 35000,
    tuitionAvg: 'PLN 2 000–5 000 семестр (~$500–1 200)',
    image: 'https://images.unsplash.com/photo-1519832979-6fa011b87667?auto=format&fit=crop&q=80&w=1200',
    logo: 'PW',
    mission: 'Воспитание инженеров нового поколения, соответствующих вызовам современного мира.',
    programs: [
      { name: 'Computer Science (B.Sc.)', degree: 'Bachelor', duration: '3.5 года', language: 'English', description: 'Разработка ПО, AI, сети.' },
      { name: 'Civil Engineering', degree: 'Bachelor', duration: '3.5 года', language: 'English/Polski', description: 'Конструкции, дороги, ЖКХ.' },
      { name: 'Electrical Engineering', degree: 'Bachelor', duration: '3.5 года', language: 'English', description: 'Энергетика, схемотехника, автоматизация.' },
      { name: 'Mechatronics', degree: 'Bachelor', duration: '3.5 года', language: 'English', description: 'Робототехника, механика, электроника.' },
    ],
    partners: ['Airbus', 'Samsung', 'Intel', 'Siemens', 'ABB'],
    admissionDeadlines: '30.06 (осенний семестр)',
    category: 'International',
    achievements: [
      'Лучший политехнический вуз Польши',
      'Диплом ЕС — признаётся в 27 странах',
      'Самый доступный техн. вуз Европы для иностранцев',
    ],
    admissionRequirements: [
      'Аттестат о среднем образовании (нострификация)',
      'IELTS 5.5+ / TOEFL iBT 72+ (для англ. программ)',
      'Польский B1+ (для польскоязычных программ)',
      'Мотивационное письмо',
    ],
    admissionProcedure: [
      'Онлайн заявка на rekrutacja.pw.edu.pl.',
      'Нострификация аттестата в Польше (~1 месяц).',
      'Оплата вступительного взноса.',
      'Получение подтверждения о зачислении.',
      'Оформление национальной визы D.',
    ],
    scholarships: [
      'Стипендия им. Банача для иностранцев (польское правительство)',
      'Polish National Agency for Academic Exchange (NAWA)',
      'Внутренние гранты политехники за успеваемость',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.pw.edu.pl',
      phone: '+48 22 234 7211',
      email: 'international@pw.edu.pl',
      address: 'Pl. Politechniki 1, 00-661 Warszawa, Poland',
    }
  },

  // --- Беларусь ---
  {
    id: 'bsuir',
    name: 'Белорусский государственный университет информатики и радиоэлектроники',
    shortName: 'БГУИР',
    location: 'Беларусь, Минск',
    description: 'Ведущий IT-университет Беларуси, один из лучших технических вузов СНГ. Чрезвычайно популярен среди казахстанцев: обучение на русском языке, низкие цены, общежития, диплом признаётся в Казахстане. Сильные программы по информатике, электронике и телекоммуникациям.',
    founded: 1964,
    ranking: 1200,
    students: 16000,
    tuitionAvg: 'от $1 800 – 2 500/год',
    image: 'https://images.unsplash.com/photo-1609769408344-ce7a49ce4e4b?auto=format&fit=crop&q=80&w=1200',
    logo: 'БГУИР',
    mission: 'Подготовка специалистов в области IT и радиоэлектроники мирового уровня.',
    programs: [
      { name: 'Программная инженерия', degree: 'Bachelor', duration: '4 года', language: 'RU', description: 'Разработка ПО, web, mobile, DevOps.' },
      { name: 'Информационная безопасность', degree: 'Bachelor', duration: '5 лет', language: 'RU', description: 'Кибербезопасность, криптография, сети.' },
      { name: 'Телекоммуникации', degree: 'Bachelor', duration: '4 года', language: 'RU', description: 'Сети связи, 5G, оптоволокно.' },
      { name: 'Электронные системы', degree: 'Bachelor', duration: '4 года', language: 'RU', description: 'Схемотехника, микроэлектроника, ПЛИС.' },
    ],
    partners: ['EPAM Systems', 'Yandex', 'Mail.ru', 'IBA Group'],
    admissionDeadlines: '25.08 (основной этап)',
    category: 'International',
    achievements: [
      'Лучший IT-вуз Беларуси',
      'Диплом признаётся в РК без нострификации',
      'Центральный вуз ПВТ — Парка высоких технологий Минска',
    ],
    admissionRequirements: [
      'Аттестат о среднем образовании',
      'ЦТ Беларуси или вступительные испытания БГУИР',
      'Знание русского языка (уровень общения)',
      'Медицинская справка',
    ],
    admissionProcedure: [
      'Подача заявки напрямую в приёмную комиссию БГУИР.',
      'Предоставление аттестата, паспорта, медсправки.',
      'Вступительные испытания или зачёт баллов ЕНТ.',
      'Заключение договора на обучение.',
      'Оформление разрешения на временное проживание в Беларуси.',
    ],
    scholarships: [
      'Квота Правительства Беларуси для иностранцев',
      'Скидки за высокий балл ЕНТ',
      'Стипендия БГУИР за отличную успеваемость',
      'Льготы для граждан стран СНГ',
    ],
    dormitory: true,
    militaryDept: false,
    contacts: {
      website: 'https://www.bsuir.by',
      phone: '+375 17 293-88-16',
      email: 'inter@bsuir.by',
      address: 'ул. П. Бровки, 6, г. Минск, 220013, Беларусь',
    }
  },
];


export const PROFESSIONS: Profession[] = [
  {
    id: 'backend-dev',
    title: 'Backend Разработчик',
    category: 'IT',
    description: 'Специалист, занимающийся разработкой серверной части веб-приложений, баз данных и API. Отвечает за логику работы сайта, скорость и безопасность данных.',
    salary: { min: 350000, max: 1500000, avg: 650000 },
    demand: 'High',
    skills: ['Python/Java/Go', 'SQL (PostgreSQL)', 'Docker', 'API Design', 'Git'],
    tasks: ['Проектирование архитектуры БД', 'Написание API', 'Оптимизация запросов', 'Настройка серверов'],
    programKeywords: ['Computer Science', 'Software', 'Информационные системы', 'ВТ и ПО']
  },
  {
    id: 'data-analyst',
    title: 'Data Analyst',
    category: 'IT',
    description: 'Специалист, который собирает, обрабатывает и интерпретирует данные для помощи бизнесу в принятии решений.',
    salary: { min: 300000, max: 1200000, avg: 550000 },
    demand: 'High',
    skills: ['SQL', 'Python (Pandas)', 'Power BI/Tableau', 'Excel', 'Статистика'],
    tasks: ['Сбор и очистка данных', 'Построение дашбордов', 'A/B тестирование', 'Прогнозирование метрик'],
    programKeywords: ['Big Data', 'Mathematics', 'Анализ данных', 'Статистика', 'Информационные системы']
  },
  {
    id: 'petroleum-eng',
    title: 'Инженер-нефтяник',
    category: 'Engineering',
    description: 'Инженер, занимающийся разработкой и эксплуатацией нефтяных и газовых месторождений. Ключевая профессия для экономики Казахстана.',
    salary: { min: 400000, max: 2000000, avg: 800000 },
    demand: 'Medium',
    skills: ['Геология', 'Гидродинамика', 'English (Technical)', 'Бурение', 'HSE'],
    tasks: ['Проектирование скважин', 'Контроль добычи', 'Анализ пластов', 'Работа на месторождении'],
    programKeywords: ['Petroleum', 'Нефтегазовое дело', 'Геология', 'Бурение']
  },
  {
    id: 'surgeon',
    title: 'Хирург',
    category: 'Medical',
    description: 'Врач-специалист, занимающийся лечением заболеваний путем оперативного вмешательства.',
    salary: { min: 250000, max: 1000000, avg: 450000 },
    demand: 'High',
    skills: ['Анатомия', 'Стрессоустойчивость', 'Мелкая моторика', 'Диагностика'],
    tasks: ['Проведение операций', 'Диагностика пациентов', 'Ведение послеоперационного периода'],
    programKeywords: ['Медицина', 'Общая медицина', 'Лечебное дело']
  },
  {
    id: 'marketer',
    title: 'Digital Маркетолог',
    category: 'Business',
    description: 'Специалист по продвижению товаров и услуг в цифровой среде (соцсети, поисковики, медиа).',
    salary: { min: 200000, max: 800000, avg: 400000 },
    demand: 'High',
    skills: ['SMM', 'SEO', 'Targeting', 'Copywriting', 'Analytics'],
    tasks: ['Запуск рекламных кампаний', 'Анализ рынка', 'Ведение соцсетей', 'Создание контент-плана'],
    programKeywords: ['Marketing', 'Маркетинг', 'Management', 'Менеджмент']
  },
  {
    id: 'architect',
    title: 'Архитектор',
    category: 'Creative',
    description: 'Специалист, проектирующий здания, интерьеры и городские пространства.',
    salary: { min: 250000, max: 900000, avg: 420000 },
    demand: 'Medium',
    skills: ['AutoCAD/Revit', '3ds Max', 'Композиция', 'Знание СНиПов'],
    tasks: ['Разработка чертежей', '3D визуализация', 'Авторский надзор', 'Согласование проектов'],
    programKeywords: ['Архитектура', 'Дизайн', 'Architecture']
  },
  {
    id: 'accountant',
    title: 'Бухгалтер',
    category: 'Finance',
    description: 'Специалист по финансовому учету, налогам и отчетности компании.',
    salary: { min: 180000, max: 600000, avg: 300000 },
    demand: 'High',
    skills: ['1C', 'Налоговый кодекс', 'Excel', 'Аудит', 'Внимательность'],
    tasks: ['Ведение учета', 'Сдача налоговой отчетности', 'Расчет зарплат', 'Работа с контрагентами'],
    programKeywords: ['Accounting', 'Учет и аудит', 'Finance', 'Финансы']
  },
  {
    id: 'teacher-math',
    title: 'Учитель математики',
    category: 'Education',
    description: 'Педагог, преподающий математику в школах, колледжах или учебных центрах.',
    salary: { min: 200000, max: 500000, avg: 320000 },
    demand: 'High',
    skills: ['Педагогика', 'Математика', 'Психология', 'Методика преподавания'],
    tasks: ['Проведение уроков', 'Подготовка к ЕНТ/Олимпиадам', 'Проверка работ'],
    programKeywords: ['Mathematics', 'Математика', 'Педагогика']
  },
  {
    id: 'agronomist',
    title: 'Агроном',
    category: 'Agriculture',
    description: 'Специалист сельского хозяйства, занимающийся выращиванием растений и повышением урожайности.',
    salary: { min: 250000, max: 700000, avg: 380000 },
    demand: 'Medium',
    skills: ['Биология', 'Химия', 'Почвоведение', 'Технологии полива'],
    tasks: ['Планирование посевов', 'Защита растений', 'Контроль сбора урожая'],
    programKeywords: ['Агрономия', 'Биотехнология']
  },
  {
    id: 'electrician',
    title: 'Инженер-энергетик',
    category: 'Engineering',
    description: 'Инженер, отвечающий за проектирование, монтаж и эксплуатацию систем электроснабжения.',
    salary: { min: 300000, max: 800000, avg: 450000 },
    demand: 'High',
    skills: ['Электротехника', 'AutoCAD', 'ПБ и ОТ', 'Схемотехника'],
    tasks: ['Проектирование сетей', 'Обслуживание оборудования', 'Энергоаудит'],
    programKeywords: ['Электроэнергетика', 'Теплоэнергетика', 'Power Engineering']
  }
];

export const FEATURES_DATA = [
  { id: 1, title: 'Об университете', desc: 'Миссия, история, лидерство', icon: 'BookOpen' },
  { id: 2, title: 'Академ. программы', desc: 'Перечень специальностей и курсов', icon: 'GraduationCap' },
  { id: 3, title: 'Приём и поступление', desc: 'Требования, сроки, гранты', icon: 'FileCheck' },
  { id: 4, title: 'Фотогалерея', desc: 'Жизнь кампуса в фотографиях', icon: 'ImageIcon' },
  { id: 5, title: 'Международное сотрудничество', desc: 'Обмен, партнеры, стажировки', icon: 'Globe2' },
  { id: 6, title: 'Функция сравнения', desc: 'Анализ и сравнение вузов', icon: 'GitCompare' },
];
